[metadata]
name = siglip-embedding-service
version = 0.1.0
description = FastAPI microservice for SigLIP text and image embeddings
author = Joseph
long_description = file: README.md
long_description_content_type = text/markdown

[options]
python_requires = >=3.8
packages = find:
install_requires =
    torch
    transformers
    pillow
    sentencepiece
    protobuf
    torchvision
    fastapi
    uvicorn[standard]
    python-multipart
    python-dotenv

[options.packages.find]
where = .
exclude =
    venv*
    .git*
    __pycache__
    *.egg-info
    tests*
